export const AdAction = {
  SET_AD_VOLUME: 'SET_AD_VOLUME',
  REQUEST_ADS: 'REQUEST_ADS',
  RESUME_AD: 'RESUME_AD',
  PAUSE_AD: 'PAUSE_AD',
  START_AD: 'START_AD',
  CONTENT_COMPLETE: 'CONTENT_COMPLETE'
}

export const AdEventType = {
  LOADED: 'LOADED',
  STARTED: 'STARTED',
  COMPLETE: 'COMPLETE',
  TAPPED: 'TAPPED',
  CLICKED: 'CLICKED',
  PAUSED: 'PAUSED',
  RESUME: 'RESUME'
}
